from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_settings_model = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_settings_model.setObjectName("groupBox_settings_model")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_settings_model)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sensivity_label = QtWidgets.QLabel(self.groupBox_settings_model)
        self.sensivity_label.setObjectName("sensivity_label")
        self.verticalLayout_3.addWidget(self.sensivity_label)
        self.sensivity_slider = QtWidgets.QSlider(self.groupBox_settings_model)
        self.sensivity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sensivity_slider.setObjectName("sensivity_slider")
        self.verticalLayout_3.addWidget(self.sensivity_slider)
        self.sensitivity_value_label = QtWidgets.QLabel(self.groupBox_settings_model)
        self.sensitivity_value_label.setText("")
        self.sensitivity_value_label.setObjectName("sensitivity_value_label")
        self.verticalLayout_3.addWidget(self.sensitivity_value_label)
        self.label_path_logs = QtWidgets.QLabel(self.groupBox_settings_model)
        self.label_path_logs.setObjectName("label_path_logs")
        self.verticalLayout_3.addWidget(self.label_path_logs)
        self.log_path_edit = QtWidgets.QLineEdit(self.groupBox_settings_model)
        self.log_path_edit.setObjectName("log_path_edit")
        self.verticalLayout_3.addWidget(self.log_path_edit)
        self.log_path_button = QtWidgets.QPushButton(self.groupBox_settings_model)
        self.log_path_button.setObjectName("log_path_button")
        self.verticalLayout_3.addWidget(self.log_path_button)
        self.gridLayout.addWidget(self.groupBox_settings_model, 0, 4, 1, 1)
        self.widget_list = QtWidgets.QWidget(self.centralwidget)
        self.widget_list.setObjectName("widget_list")
        self.formLayout = QtWidgets.QFormLayout(self.widget_list)
        self.formLayout.setObjectName("formLayout")
        self.list_label = QtWidgets.QLabel(self.widget_list)
        self.list_label.setObjectName("list_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.list_label)
        self.defective_board_list = QtWidgets.QListWidget(self.widget_list)
        self.defective_board_list.setObjectName("defective_board_list")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.defective_board_list)
        self.gridLayout.addWidget(self.widget_list, 3, 1, 1, 2)
        self.video_frame = QtWidgets.QLabel(self.centralwidget)
        self.video_frame.setEnabled(True)
        self.video_frame.setMinimumSize(QtCore.QSize(640, 640))
        self.video_frame.setMaximumSize(QtCore.QSize(640, 640))
        self.video_frame.setText("")
        self.video_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.video_frame.setObjectName("video_frame")
        self.gridLayout.addWidget(self.video_frame, 0, 0, 2, 4)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_label = QtWidgets.QLabel(self.widget)
        self.result_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        self.result = QtWidgets.QLabel(self.widget)
        self.result.setText("")
        self.result.setObjectName("result")
        self.verticalLayout.addWidget(self.result)
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_settings_model.setTitle(_translate("MainWindow", "Панель настроек"))
        self.sensivity_label.setText(_translate("MainWindow", "Чувствительность модели:"))
        self.label_path_logs.setText(_translate("MainWindow", "Путь для сохранения логов:"))
        self.log_path_button.setText(_translate("MainWindow", "Выбрать путь..."))
        self.list_label.setText(_translate("MainWindow", "Список последних проверенных плат с результатами анализа:"))
        self.result_label.setText(_translate("MainWindow", "Результат анализа платы (годная/брак):"))
        self.save_button.setText(_translate("MainWindow", "Сохранить изображение брака"))